Update inertial attitude ukf to accept IMUSensorMsgPayload
lasp/xmera pull request #349
Opened 2024-09-27 22:57 UTC by leahkiner

* **Tickets addressed:** bsk-348
* **Review:** By commit
* **Merge strategy:** Merge (no squash)  

## Description
This PR refactors the `inertialAttitudeUkf` module to accept the `STSensorMsgPayload` message. Currently, the `inertialAttitudeUkf` module accepts the `AccDataMsgPayload` message. A separate converter module will be PRd on the ema-gnc repository to convert from the `AccDataMsgPayload` message to the `STSensorMsgPayload` message.

## Verification
N/A

## Documentation
N/A

## Future work
N/A

2024-09-28 02:43 UTC, thibaudteil requested changes, later dismissed
You'll have to update the test to read the ImuSensor message.

2025-05-12 21:57 UTC, patkenneally requested changes
:small_red_triangle_down: *Issues* to address before merge
:large_orange_diamond: *Requests* that should not block merge, but should at least be discussed
:large_blue_circle: *Recommendations* that can be ignored if desired

2025-05-12 21:57 UTC, patkenneally commented on src/fswAlgorithms/attDetermination/inertialAttitudeUkf/inertialAttitudeUkf.i
> +struct IMUSensorMsg_C;
:small_red_triangle_down: All these `struct XXX_C;` lines should be deleted. They do nothing because there is no longer C messaging functionality.

2025-05-12 21:57 UTC, patkenneally commented on src/fswAlgorithms/sensorInterfaces/miruLowPassFilterConverter/miruLowPassFilterConverter.h
> +    void Reset(uint64_t CurrentSimNanos);                           //!< Reset member function
:small_red_triangle_down: These `reset` and `updateState` should have `override` added to their declaration. In their current state they would be called. Can also change `CurrentSimNanos` to `currentSimNanos`

2025-05-12 21:57 UTC, patkenneally commented on src/simulation/sensors/imuSensor/imuSensor.cpp
> +    localOutput.timeTag = Clock*1E-9;
:large_orange_diamond: Any value in using the `NANO2SEC` macros here and below?

2025-05-12 21:57 UTC, patkenneally commented on src/fswAlgorithms/attDetermination/inertialAttitudeUkf/inertialAttitudeUkf.cpp
> +        this->previousWheelSpeeds = Eigen::Map<Eigen::Matrix<double, 1, 4>>(rwSpeedPayload.wheelSpeeds);
:small_red_triangle_down: Should this be an Xd?

2025-05-12 21:57 UTC, patkenneally commented on src/simulation/sensors/imuSensor/imuSensor.cpp
> +ImuSensor::~ImuSensor() { return; }
:large_orange_diamond: Some redundant `return;` statements in the set and destructor methods. Up to you. Actually, a bunch of redundant return statements in the module generally. Maybe we'll do them in a separate refactor.

2025-05-15 23:45 UTC, thibaudteil commented on src/fswAlgorithms/attDetermination/inertialAttitudeUkf/inertialAttitudeUkf.i
> +struct IMUSensorMsg_C;
removed!

2025-05-15 23:50 UTC, thibaudteil commented on src/fswAlgorithms/sensorInterfaces/miruLowPassFilterConverter/miruLowPassFilterConverter.h
> +    void Reset(uint64_t CurrentSimNanos);                           //!< Reset member function
done

2025-05-15 23:54 UTC, thibaudteil commented on src/simulation/sensors/imuSensor/imuSensor.cpp
> +    localOutput.timeTag = Clock*1E-9;
why not? Added

2025-05-16 00:01 UTC, thibaudteil commented on src/fswAlgorithms/attDetermination/inertialAttitudeUkf/inertialAttitudeUkf.cpp
> +        this->previousWheelSpeeds = Eigen::Map<Eigen::Matrix<double, 1, 4>>(rwSpeedPayload.wheelSpeeds);
fixed

2025-05-16 00:05 UTC, thibaudteil commented on src/simulation/sensors/imuSensor/imuSensor.cpp
> +ImuSensor::~ImuSensor() { return; }
fixed

2025-06-02 17:22 UTC, patkenneally approved these changes

2025-06-02 17:22 UTC, patkenneally commented on src/fswAlgorithms/attDetermination/inertialAttitudeUkf/inertialAttitudeUkf.cpp
> +            Eigen::MatrixXd dcm_CB = cArray2EigenMatrix3d(starTracker.dcm_CB);
:large_orange_diamond: Should this type be `Eigen::Matrix3d`?

2025-06-02 17:22 UTC, patkenneally commented on src/fswAlgorithms/attDetermination/inertialAttitudeUkf/inertialAttitudeUkf.cpp
> +        Eigen::Matrix3d switchMatrix = 2 * std::pow(sigma.norm(), 4) * sigma * sigma.transpose() -
:large_orange_diamond: Worth factoring out this duplicate code into a method?

2025-06-03 16:50 UTC, thibaudteil commented on src/fswAlgorithms/attDetermination/inertialAttitudeUkf/inertialAttitudeUkf.cpp
> +            Eigen::MatrixXd dcm_CB = cArray2EigenMatrix3d(starTracker.dcm_CB);
yes it should!

2025-06-03 19:46 UTC, thibaudteil commented on src/fswAlgorithms/attDetermination/inertialAttitudeUkf/inertialAttitudeUkf.cpp
> +        Eigen::Matrix3d switchMatrix = 2 * std::pow(sigma.norm(), 4) * sigma * sigma.transpose() -
yes, I can do that

2025-06-03 21:41 UTC, merged